# Generated by Django 5.2.1 on 2025-05-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applications', '0001_initial'),
        ('Jobs', '0002_initial'),
        ('Resume', '0001_initial'),
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Jobs.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='UserAuth.jobseekerprofile', verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user', 'job', 'interaction_type')},
        ),
    ]
