# Generated by Django 5.2.1 on 2025-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the job listing', max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Rem', 'Remote'), ('PT', 'Part-Time'), ('FT', 'Full-Time')], max_length=3)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('transport', 'Transportation & Logistics'), ('legal', 'Legal'), ('marketing', 'Marketing & Advertising'), ('consulting', 'Consulting'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('energy', 'Energy & Utilities'), ('government', 'Government'), ('nonprofit', 'Nonprofit'), ('media', 'Media & Entertainment'), ('agriculture', 'Agriculture'), ('telecom', 'Telecommunications'), ('aerospace', 'Aerospace & Defense')], max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Job',
                'ordering': ['-posted_at', 'is_active'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
    ]
