version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"  
    env_file:
      - .env 
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000  

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: jobDB      
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: azerty 

  redis:
    image: redis:7-alpine
    restart: always

  celery:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A jobRecommandation worker -l info --pool=solo

  celery-beat:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A jobRecommandation beat -l info

volumes:
  postgres_data:
