# Generated by Django 5.2.1 on 2025-05-20 09:49

import Resume.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[Resume.models.resume_format_validator])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'Resume',
                'ordering': ['uploaded_at', 'is_verified'],
            },
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('experience_summary', models.TextField(blank=True, null=True)),
                ('education_summary', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resume.resume', verbose_name='Resume File')),
                ('skills', models.ManyToManyField(blank=True, to='Jobs.skill')),
            ],
            options={
                'db_table': 'ResumeData',
            },
        ),
    ]
