# Generated by Django 5.2.1 on 2025-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('precision_at_5', models.FloatField()),
                ('sample_size', models.IntegerField()),
            ],
            options={
                'db_table': 'RecommendationMetrics',
                'ordering': ['-date'],
            },
        ),
    ]
