# Generated by Django 5.2.1 on 2025-06-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_initial'),
        ('Recommendations', '0002_recommendationmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
    ]
