# Generated by Django 5.2.1 on 2025-05-20 10:23

import UserAuth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', UserAuth.models.CustomUserManager()),
            ],
        ),
    ]
